config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'

  post '/login', to: 'pages#create_session_login'
  post '/logout', to: 'pages#destroy_session_logout'


  resources :users do
    resources :friends
    resources :galleries do
      resources :images
      resources :settings
    end
  end
    get '/users/:id/profile', to: 'users#show_your_profile', as: 'show_your_profile'
    get '/new_friend_confirmation', to: 'friends#new_friend_confirmation', as: 'new_friend_confirmation'


  get '/view_galleries/search', to: 'galleries#search_for_galleries', as: "search_for_galleries"
  post '/view_galleries/search', to: "galleries#search_results", as: "search_results"
  # also, need a GET route for the search-results page??
  get '/view_galleries/:id', to: 'galleries#view_published_gallery', as: "view_published_gallery"
  get '/view_galleries/:id/image_details', to: 'galleries#view_image_details', as: "view_image_details"


  # deletion and deletion-confirmation-page routes
  get '/users/:id/user_deleted', to: 'users#user_deleted', as: "user_deleted"
  get '/users/:id/friends/:id/friend_deleted', to: 'friends#friend_deleted', as: "friend_deleted"
  get '/users/:id/galleries/:id/gallery_deleted', to: 'galleries#gallery_deleted', as: "gallery_deleted"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :galleries
  has_many :images, through: :galleries
  has_many :settings, through: :galleries
  has_many :friends

  validates :user_name, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, except: [:edit, :update, :destroy]

  def index
    @users = User.order("LOWER(users.user_name) ASC").references(:users)
  end

  # visitor show page
  def show
    if params[:id] == session[:user_id].to_s
      render :show_your_profile
    else
      @user = User.find(params[:id])
    end
  end

  # show your own profile
  def show_your_profile
    if params[:id] != session[:user_id].to_s
      redirect_to user_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to current_user
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to current_user
    else
      flash[:error] = current_user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    current_user.destroy
    redirect_to user_deleted_path
  end

  def user_deleted
  end


  def seed_create=(user_params)
    @user = User.create(user_params)
  end



  around_action :catch_not_found

  private



  def user_params
    params.require(:user).permit!
  end

  def catch_not_found
    yield
  rescue ActiveRecord::RecordNotFound
    flash[:message] = "User not found - redirected to main page."
    redirect_to root_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
<br><br><br>

<div><h2>Edit Your Profile:</h2></div>

<div>
  <% if current_user.errors.any? %>
    <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% current_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
</div>

<div>
  <%= form_for(current_user) do |f| %>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %><br><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <br><br>
    <h4>Optional Data:</h4>
    <%= f.label :real_name %>
    <%= f.text_field :real_name %><br><br>
    <%= f.label :location %>
    <%= f.text_field :location %><br><br>
    <%= f.label :age %>
    <%= f.number_field :age %><br><br>
    <%= f.label :blurb %>
    <%= f.text_area :blurb %><br><br>
    <%= f.submit %>
  <% end  %>
</div>

<br>
<div>
  <h5><%= link_to 'Delete User', user_path, method: 'delete' %></h5>
</div>

<br>
<div>
  <h5><%= link_to 'Back to Your Profile', user_path(current_user.id) %></h5>
</div>

<br><br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>

app/views/users/index.erb
<body>

  <br><br><br>

  <div>
    <h2>Browse Users</h2>
    You can add them to your Friends!
  </div>
  <br><br>

  <br>
  <h3>All Users:</h3>
  <font size=4>
    <div>
      <% @users.each do |user| %>
        <%= link_to user.user_name, show_your_profile_path(user) %><br><br>
      <% end %>
    </div>
  </font>

  <br><br><br>
  <div>
    <h4><%= link_to 'Create New User', new_user_path %></h4>
  </div>

  <br><br><br>
  <div>
    <h4><%= link_to 'Back to Main Page', root_path %></h4>
  </div>

</body>

app/views/users/new.erb
<br><br><br>

<div><h2>New User</h2></div>

<div>
  <% if @user.errors.any? %>
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
</div>

<div>
  <%= form_for(@user) do |f| %>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %><br><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br><br><br>
    <h4>Optional Data:</h4>
    <%= f.label :real_name %>
    <%= f.text_field :real_name %><br><br>
    <%= f.label :location %>
    <%= f.text_field :location %><br><br>
    <%= f.label :age %>
    <%= f.number_field :age %><br><br>
    <%= f.label :blurb %>
    <%= f.text_area :blurb %><br><br><br>
    <%= f.submit %>
  <% end  %>
</div>

<br><br><br>

app/views/users/show.erb
<br><br><br>

<div>
  <h2><%= @user.user_name %></h2>
  Real Name: <%= @user.real_name %><br>
  Location: <%= @user.location %><br>
  Age: <%= @user.age %><br>
  Blurb: <%= @user.blurb %><br>
  <br>
<div>

<div>
  <h3>Galleries by <%= @user.user_name %></h3>
  <% @user.galleries.each do |gallery| %>
    <%= link_to gallery.name, view_published_gallery_path(gallery.id) %><br><br>
  <% end %>
</div>

<br>
<div>
  <h3><%= @user.user_name %>'s Friends:</h3>
  <% friends_array = Friend.where(owner_user_id: @user.id) %>
  <% if friends_array.any? %>
    <% friends_array.each do |friend_join| %>
      <% if User.exists?(friend_join.target_user_id) %>
        <% user_friend = User.find(friend_join.target_user_id) %>
          <%= link_to user_friend.user_name, user_path(user_friend) %><br><br>
      <% end %>
    <% end %>
  <% else %>
    No friends yet!
  <% end %>
</div>


<br>
<% if logged_in? %>
  <br>
  <div>
    <h5><%= link_to 'Add This User to Your Friends', new_user_friend_path(current_user, params[:id] = @user.id) %></h5>
  </div>
<% end %>

<br><br><br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>

<br><br><br>

<% if flash[:message] %>
  <%= flash[:message] %>
<% end %>

app/views/users/show_your_profile.erb
<br><br><br>

<div>
  <h2><%= current_user.user_name %></h2>
  Real Name: <%= current_user.real_name %><br>
  Location: <%= current_user.location %><br>
  Age: <%= current_user.age %><br>
  Blurb: <%= current_user.blurb %><br>
  <br>
<div>

<div>
  <h5><%= link_to 'Edit Your Profile', edit_user_path(current_user) %></h5>
</div>

<br><br>
<div>
  <h3>Edit your Galleries:</h3>
  <% current_user.galleries.each do |gallery| %>
    <%= link_to gallery.name, user_gallery_path(current_user.id, gallery) %> - view <%= link_to 'published version', view_published_gallery_path(gallery.id) %><br><br>
  <% end %>
    <h5><%= link_to 'Create New Gallery', new_user_gallery_path(user_id: current_user.id) %></h5>
</div>

<br><br>
<div>
  <h3>Your Friends:</h3>
  <% friends_array = Friend.where(owner_user_id: current_user.id) %>
  <% if friends_array.any? %>
    <% friends_array.each do |friend_join| %>
      <% user_friend = User.find(friend_join.target_user_id) %>
      <strong><%= link_to user_friend.user_name, user_path(user_friend) %></strong> - <%= link_to "delete from Friends", user_friend_path(current_user, user_friend), method: 'delete' %><br>
    <% end %>
  <% else %>
    No friends yet!
  <% end %>
</div>

<br><br><br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>

<br><br><br>

<% if flash[:message] %>
  <%= flash[:message] %>
<% end %>

app/views/users/user_deleted.erb
<h1>User successfully deleted!</h1>

<br>
<div>
  <h2><%= link_to 'Back to Main Page', root_path %></h2>
</div>