config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'

  post '/login', to: 'pages#create_session_login'
  post '/logout', to: 'pages#destroy_session_logout'


  resources :users do
    resources :friends
    resources :galleries do
      resources :images
      resources :settings
    end
  end
    get '/users/:id/profile', to: 'users#show_your_profile', as: 'show_your_profile'
    get '/new_friend_confirmation', to: 'friends#new_friend_confirmation', as: 'new_friend_confirmation'


  get '/view_galleries/search', to: 'galleries#search_for_galleries', as: "search_for_galleries"
  post '/view_galleries/search', to: "galleries#search_results", as: "search_results"
  # also, need a GET route for the search-results page??
  get '/view_galleries/:id', to: 'galleries#view_published_gallery', as: "view_published_gallery"
  get '/view_galleries/:id/image_details', to: 'galleries#view_image_details', as: "view_image_details"


  # deletion and deletion-confirmation-page routes
  get '/users/:id/user_deleted', to: 'users#user_deleted', as: "user_deleted"
  get '/users/:id/friends/:id/friend_deleted', to: 'friends#friend_deleted', as: "friend_deleted"
  get '/users/:id/galleries/:id/gallery_deleted', to: 'galleries#gallery_deleted', as: "gallery_deleted"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  # belongs_to :user is set to Optional for testing
  # purposes - validation IS needed for final product!
  belongs_to :user
  has_many :images
  has_many :settings

  # validations below are commented out for testing reasons.
  # when these validations are applied, the galleries/new
  # form crashes, saying @user = nil (can't run @user.id)
  validates :name, presence: true
  validates :theme, presence: true

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  skip_before_action :authenticate_user, only: [:index, :show, :search_for_galleries, :search_results, :view_published_gallery, :view_image_details]

  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
    @gallery = Gallery.new
    if params[:user_id]
      # current_user is a helper method available in
      # the view (no @user object needed)

    # is this Else option only for TESTING?? can we
    # remove?? (only logged-in users should create Galleries...)
    # else
    #   @user = User.new
    #   name = "new_user_#{@user.id}"
    #   @user.user_name = name
    end
  end

  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      default_setting = Setting.create(gallery_id: @gallery.id, theme_name: "default", background_color: "white", font: "Times New Roman")
      @gallery.current_setting_id = default_setting.id
      @gallery.save
      flash[:message] = "New gallery created successfully!"
      redirect_to user_gallery_path(@gallery.user, @gallery.id)
    else
      flash[:error] = @gallery.errors.full_messages.to_sentence
      # current_user is a helper method available in
      # the view (no @user object needed)
      render :new
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update(gallery_params)
      flash[:message] = "Gallery successfully updated!"
      redirect_to user_gallery_path(@gallery.user, @gallery.id)
    else
      flash[:error] = @gallery.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @user = @gallery.user
    @gallery.destroy
    render :gallery_deleted
  end

  def gallery_deleted
  end

  def search_for_galleries
  end

  def search_results
    if params[:search][:user_name]
      @user = User.find_by(user_name: params[:search][:user_name])
      @galleries = Gallery.where(user_id: @user.id)
    elsif params[:search][:theme]
      @galleries = Gallery.where(theme: params[:search][:theme])
    elsif params[:search][:name]
      @galleries = Gallery.where(name: params[:search][:name])
    end
  end

  def view_published_gallery
  # this method will be the SHOW FINAL GALLERY route,
  # separate from having the User view it for editing
    @gallery = Gallery.find(params[:id])
    if Setting.exists?(id: @gallery.current_setting_id)
      @settings = Setting.find(@gallery.current_setting_id)
    else
      @settings = Setting.create(gallery_id: @gallery.id, theme_name: "default", background_color: "white", font: "Times New Roman")
    end
    @images = Image.where(gallery_id: @gallery.id).order(:id)
    @gallery_owner = User.find(@gallery.user_id)
  end

  def view_image_details
    @gallery = Gallery.find(params[:id])
    @settings = Setting.find(@gallery.current_setting_id)
    @images = Image.where(gallery_id: @gallery.id).order(:id)
    @gallery_owner = User.find(@gallery.user_id)
  end




  # around_action :catch_not_found

  private



  def gallery_params
    params.require(:gallery).permit!
  end

  # def catch_not_found
  #   yield
  # rescue ActiveRecord::RecordNotFound
  #   redirect_to galleries_path, :flash => { :error => "Record not found." }
  # end


end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/edit.erb
<br><br><br>

<div><h2>Edit Gallery:</h2></div>

<% @gallery = Gallery.find(params[:id])%>
<div>
  <% if @gallery.errors.any? %>
    <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>
    <ul>
    <% @gallery.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
</div>


<div>
  <%= form_tag(user_gallery_path(current_user.id, @gallery), :method => :patch) do %>
  <%= label_tag(:name)%>
  <%= text_field_tag("gallery[name]", @gallery.name) %><br>
  <%= label_tag(:theme)%>
  <%= text_field_tag("gallery[theme]",@gallery.theme) %><br>
  <%= label_tag(:blurb)%>
  <%= text_area_tag("gallery[blurb]", @gallery.blurb) %><br><br><br>
    <h3>Choose Custom Settings:</h3>
    <%= label_tag :theme_name %>
    <%= collection_select("gallery", :current_setting_id, Setting.where(gallery_id: @gallery.id), :id, :theme_name, {selected: Setting.find(@gallery.current_setting_id)}) %>
    <br><br><br>
  <%= submit_tag %>
  <% end %>
</div>



<br><br><br>
<div>
  <h4><%= link_to 'Edit Custom Settings', edit_user_gallery_setting_path(current_user.id, @gallery.id)%></h4>
</div>

<br><br>
<div>
  <h4><%= link_to 'Delete Gallery', user_gallery_path, method: 'delete' %></h4>
</div>

<br><br>
<div>
  <h4><%= link_to 'Back to Gallery', user_gallery_path(current_user.id, @gallery)%></h4>
</div>

<br><br><br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>


<br><br><br>

app/views/galleries/gallery_deleted.erb
<h1>Gallery successfully deleted!</h1>

<br>
<div>
  <h2><%= link_to "Back to Your Profile", user_path(current_user.id) %></h2>
</div>

<br>
<div>
  <h2><%= link_to 'Back to Main Page', root_path %></h2>
</div>


<br><br><br>

app/views/galleries/index.erb
<div><h1>Gallery Index</h1></div>

NOTE: the Gallery Index should ONLY be accessible through
a "Show all Galleries" portal from the main page--DO NOT
LINK this index to Gallery/User show/edit view...

<div>
  <% @galleries.each do |gallery| %>
    <h2><%= link_to "#{gallery.name} (created by #{gallery.user.user_name})", user_gallery_path(gallery) %></h2>
  <% end %>
</div>

<br><br>
<div>
  <h2><%= link_to 'Back to User Index', users_path %></h2>
</div>


<br><br><br>

app/views/galleries/new.erb
<br><br><br>

<div><h2>New Gallery</h2></div>

<div>
  <% if @gallery.errors.any? %>
    <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>
    <ul>
    <% @gallery.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
</div>

<!--
need to add in @user.id for @gallery.user_id...
add this inside squids to bottom of form:
[SQUID] f.hidden_field(:user_id, :value => @user.id) %>
(need to have the @user set up in Galleries#new method)
...
also, should we make the 'theme' field a drop-down of
pre-set options PLUS the ability to make a new one??
-->



<div>
  <%= form_tag(user_galleries_path(current_user)) do %>
    <%= label_tag(:name)%>
    <%= text_field_tag("gallery[name]") %><br>
    <%= label_tag(:theme)%>
    <%= text_field_tag("gallery[theme]") %><br>
    <%= label_tag(:blurb)%>
    <%= text_area_tag("gallery[blurb]") %><br>
    <%= hidden_field_tag 'gallery[user_id]', current_user.id %>
    <%= submit_tag "Create New Gallery" %>
  <% end %>
</div>

<br><br>
<div>
  <h4><%= link_to 'Back to your Profile', show_your_profile_path(current_user) %></h4>
</div>

<br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>


<br><br><br>

app/views/galleries/search_for_galleries.erb
<br><br><br>

<div>
  <h2>Search for galleries:</h2>
  Search by user:
    <%= form_tag(search_results_path) do %>
      <%= collection_select("search", :user_name, User.order("LOWER(users.user_name) ASC").references(:users), :user_name, :user_name) %>
      <%= submit_tag "Submit" %>
    <% end %>
    <br>
  Search by theme:
  <%= form_tag(search_results_path) do %>
    <%= collection_select("search", :theme, Gallery.order("LOWER(galleries.theme) ASC").references(:galleries), :theme, :theme) %>
    <%= submit_tag "Submit "%>
  <% end %>
  <br>
  Search by gallery name:
  <%= form_tag(search_results_path) do %>
    <%= collection_select("search", :name, Gallery.order("LOWER(galleries.name) ASC").references(:galleries), :name, :name) %>
    <%= submit_tag "Submit "%>
  <% end %>
  <br>
</div>

<br>
<div>
  <!-- need to add a Published field to Gallery model?? -->
  <h3>All published galleries:</h3>
  <% Gallery.all.each do |gallery| %>
    <p><%= link_to "#{gallery.name}", view_published_gallery_path(gallery) %> - created by <%= link_to "#{gallery.user.user_name}", user_path(gallery.user.id) %></p>
  <% end %>
</div>

<br><br><br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>


<br><br><br>

app/views/galleries/search_results.erb
<br><br><br>

<h2>Search results:</h2>

<% if @galleries.any? %>
  <% @galleries.each do |gallery| %>
    <%= link_to gallery.name, view_published_gallery_path(gallery.id) %>
  <% end %>
<% end %>

<br><br><br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>


<br><br><br>

app/views/galleries/show.erb
<br><br><br>

<div>
  <h2><%= @gallery.name %></h2>
  Created by: <%= @gallery.user.user_name %><br>
  Theme: <%= @gallery.theme %><br>
  Blurb: <%= @gallery.blurb %><br>
</div>

<br><br>
<div>
  <h4><%= link_to 'View Published Gallery', view_published_gallery_path(@gallery) %></h4>
</div>

<br>
<div>
  <p><%= link_to 'Edit Gallery Info & Change Custom Settings', edit_user_gallery_path(@gallery) %></p>
</div>

<br>
<div>
  <p><%= link_to 'Create New Custom Settings', new_user_gallery_setting_path(current_user.id, params[:id]) %></p>
</div>

<br>
<div>
  <p><%= link_to 'Edit Custom Settings', user_gallery_settings_path(current_user.id, params[:id]) %></p>
</div>

<br>
<div>
  <p><%= link_to 'Add Images to Gallery', new_user_gallery_image_path(current_user.id, @gallery.id) %></p>
</div>

<br>
<div>
  <p><%= link_to 'Edit Images in Gallery', user_gallery_images_path(current_user.id, @gallery.id) %></p>
</div>





<br>
<div>
  <p><%= link_to 'Back to User Profile', user_path(@gallery.user) %></p>
</div>

<br><br><br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>


<br><br><br>

<% if flash[:message] %>
  <%= flash[:message] %>
<% end %>

<br><br><br>

app/views/galleries/view_image_details.erb
<br><br><br>

<h2>Image Details:</h2>

<% @images.each do |image| %>

  <div>
    <%= image_tag image.image.url %><br>
    Title: <%= image.title %><br>
    Artist: <%= image.artist %><br>
    Medium: <%= image.medium %><br>
  </div>
  <br><br>

<% end %>

<br><br>
<div>
  <h4><%= link_to "Back to Gallery", view_published_gallery_path(@gallery) %></h4>
</div>

<br><br><br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>


<br><br><br>

app/views/galleries/view_published_gallery.erb
<body style="background-color:<%= @settings.background_color %>; font-family:<%= @settings.font %>">




<% if @settings.audio %>
  <iframe width="0" height="0" src="https://www.youtube.com/embed/<%=@settings.audio%>?autoplay=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<% end %>

<br><br><br>



  <h1><center><%= @gallery.name %></center></h1>


      <br><br><br><br><br>


<!-- refactor image-displays using Bootstrap! -->
<% if @images.any? %>
  <% @images.each do |image| %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-10 offset-1">
        <div class="text-center">
          <%= image_tag image.image.url, class: "img-fluid" %>
        </div>
      </div>
    </div>
  </div>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  <% end %>
<% end %>

  <br><br><br><br><br>

  <% if @gallery_owner.id == session[:user_id] %>
    <br>
    <div>
      <h3><%= link_to 'Back to Edit Gallery', user_gallery_path(current_user.id, @gallery.id)%></h3>
    </div>
  <% end %>

  <div>
    <p><%= link_to 'View Image Details', view_image_details_path(@gallery.id) %></p>
  </div>

  <div>
    <p><%= link_to "View #{@gallery.user.user_name}'s Profile", user_path(@gallery_owner) %></p>
  </div>

  <div>
    <p><%= link_to "Back to View Galleries", search_for_galleries_path %></p>
  </div>

  <div>
    <p><%= link_to "Back to Main Page", root_path %></p>
  </div>


  <br><br><br>



</body>