config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'

  post '/login', to: 'pages#create_session_login'
  post '/logout', to: 'pages#destroy_session_logout'


  resources :users do
    resources :friends
    resources :galleries do
      resources :images
      resources :settings
    end
  end
    get '/users/:id/profile', to: 'users#show_your_profile', as: 'show_your_profile'
    get '/new_friend_confirmation', to: 'friends#new_friend_confirmation', as: 'new_friend_confirmation'


  get '/view_galleries/search', to: 'galleries#search_for_galleries', as: "search_for_galleries"
  post '/view_galleries/search', to: "galleries#search_results", as: "search_results"
  # also, need a GET route for the search-results page??
  get '/view_galleries/:id', to: 'galleries#view_published_gallery', as: "view_published_gallery"
  get '/view_galleries/:id/image_details', to: 'galleries#view_image_details', as: "view_image_details"


  # deletion and deletion-confirmation-page routes
  get '/users/:id/user_deleted', to: 'users#user_deleted', as: "user_deleted"
  get '/users/:id/friends/:id/friend_deleted', to: 'friends#friend_deleted', as: "friend_deleted"
  get '/users/:id/galleries/:id/gallery_deleted', to: 'galleries#gallery_deleted', as: "gallery_deleted"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :gallery
  # validates :title, presence: true
  # validates :artist, presence: true
  # validates :medium,  presence: true

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  skip_before_action :authenticate_user, only: [:index]

  def index
    @images = Image.where(gallery_id: params[:gallery_id])
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to user_gallery_images_path
    else
      flash[:error] = @image.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to user_gallery_images_path(current_user.id, params[:gallery_id])
    else
      flash[:error] = @image.errors.full_messages.to_sentence
      render :edit
  end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to user_gallery_images_path(current_user.id, params[:gallery_id])
  end

  private

  def image_params
    params.require(:image).permit!
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.erb
<br><br><br>

<h2>Edit image</h2>
<%@image = Image.find(params[:id])%>
<%=form_tag(user_gallery_image_path(current_user.id, params[:gallery_id], @image), :method => :patch) do %>
<%=label_tag :title%>
<%=text_field_tag "image[title]", @image.title%>
<%=label_tag :artist%>
<%=text_field_tag "image[artist]", @image.artist%>
<%=label_tag :medium%>
<%=text_field_tag "image[medium]", @image.medium%>
<%=submit_tag "submit"%>
<%end%>

app/views/images/index.erb
<br><br><br>

<h2>All images in this gallery:</h2>

<% @images.each do |image| %>

  <div>
    <%= image_tag image.image.url %><br>
    Title: <%= image.title %><br>
    Artist: <%= image.artist %><br>
    Medium: <%= image.medium %><br>

      <%= link_to "Edit Image Info", edit_user_gallery_image_path(current_user, params[:gallery_id], image) %><br>
      <%= link_to "Delete Image", user_gallery_image_path(current_user, params[:gallery_id], image), method: 'delete' %>

  </div>
  <br><br>

<% end %>

<br>
<div>
  <p><%= link_to 'Add Images to Gallery', new_user_gallery_image_path(current_user.id, params[:gallery_id]) %></p>
</div>

<br><br>
<div>
  <h4><%= link_to 'View Published Gallery', view_published_gallery_path(params[:gallery_id]) %></h4>
</div>

<br><br>
<div>
  <h4><%= link_to 'Back to Main Page', root_path %></h4>
</div>

<br><br><br>

app/views/images/new.erb
<br><br><br>

<h2>Create new image</h2>

<div>
  <% if @image.errors.any? %>
    <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>
    <ul>
    <% @image.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
</div>

<%= form_tag(user_gallery_images_path(current_user, params[:gallery_id]), :multipart => true) do %>
  <%= label_tag(:image)%>
  <%= file_field_tag("image[image]") %><br>
  <%= label_tag(:title)%>
  <%= text_field_tag("image[title]") %><br>
  <%= label_tag(:artist)%>
  <%= text_field_tag("image[artist]") %><br>
  <%= label_tag(:medium)%>
  <%= text_field_tag("image[medium]") %><br>
  <%= hidden_field_tag "image[gallery_id]", params[:gallery_id].to_i %>
  <%= submit_tag %>
<% end %>

<br><br>
<div>
  <%= link_to "Back to Edit Gallery", user_gallery_path(current_user, params[:gallery_id]) %>
</div>


<br><br><br>

app/views/images/show.erb
<br><br><br>

<h2>See image</h2>
<%=@image.title%>
<%=@image.artist%>
<%=@image.medium%>
<%=@image.link%>

<%= image_tag @image.image.url %>



<br><br><br>