config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'

  post '/login', to: 'pages#create_session_login'
  post '/logout', to: 'pages#destroy_session_logout'


  resources :users do
    resources :friends
    resources :galleries do
      resources :images
      resources :settings
    end
  end
    get '/users/:id/profile', to: 'users#show_your_profile', as: 'show_your_profile'
    get '/new_friend_confirmation', to: 'friends#new_friend_confirmation', as: 'new_friend_confirmation'


  get '/view_galleries/search', to: 'galleries#search_for_galleries', as: "search_for_galleries"
  post '/view_galleries/search', to: "galleries#search_results", as: "search_results"
  # also, need a GET route for the search-results page??
  get '/view_galleries/:id', to: 'galleries#view_published_gallery', as: "view_published_gallery"
  get '/view_galleries/:id/image_details', to: 'galleries#view_image_details', as: "view_image_details"


  # deletion and deletion-confirmation-page routes
  get '/users/:id/user_deleted', to: 'users#user_deleted', as: "user_deleted"
  get '/users/:id/friends/:id/friend_deleted', to: 'friends#friend_deleted', as: "friend_deleted"
  get '/users/:id/galleries/:id/gallery_deleted', to: 'galleries#gallery_deleted', as: "gallery_deleted"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GallerySpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-dark bg-primary">

      <div class="row">
        <div class="col">
            <a class="navbar-brand" href="/">
              <h1>GallerySpace</h1>
            </a>
          </div>
        </div>

        <div class="row">
          <div class="col">
          </div>
        </div>

        <div class="row">
          <div class="col">
          </div>
        </div>

        <div class="row">
          <div class="col">
          </div>
        </div>

        <div class="row">
          <div class="col-1 offset-10">
            <a class="navbar-brand" href="<%= search_for_galleries_path %>">
              View Galleries
            </a>
          </div>
        </div>

        <div class="row">
          <div class="col-1 offset-6">
            <a class="navbar-brand" href="<%= users_path %>">
              Browse Users
            </a>
          </div>
        </div>

        <div class="row">
          <div class="col", align="right">
            <font color=white size=4>
              <% if !logged_in? %>
                <%= form_tag(login_path) do %>
                  <%= label_tag :user_name %>
                  <%= text_field_tag :user_name %><br>
                  <%= label_tag :password %>
                  <%= password_field_tag :password %><br>
                  <%= submit_tag "Login" %>
                <% end %>
              <% else %>
                <a href="/users/<%= current_user.id %>" class="navbar-brand">
                You are logged in as <%= current_user.user_name %>.<br>
                Click here to go to your profile.<br>
                </a>
                <%= form_tag(logout_path) do %>
                  <%= submit_tag "Logout" %>
                <% end %>
              <% end %>

            </font>
          </div>
        </div>

    </nav>
    <br><br><br>


    <nav class="navbar {min-height: 50px} fixed-bottom navbar-dark botbar">



      <div class="row">
        <div class="col">
          <font color=white>
            Created by Isa Levine and Chris Cable, in tribute to a simpler era of the Internet.
          </font>
        </div>
      </div>

      <div class="row">
        <div class="col">
        </div>
      </div>

      <div class="row">
        <div class="col">
          <font color=white>
            Rest in peace, MySpace & GeoCities...
          </font>
        </div>
      </div>

    </nav>








    <%= yield %>
  </body>



  <!-- <footer>
    Links to navigate around site??
  </footer> -->

</html>